# Generated by Django 3.2.9 on 2021-11-21 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
        migrations.AlterField(
            model_name='application',
            name='close_date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
        migrations.AlterField(
            model_name='job',
            name='open_date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
    ]
