# Generated by Django 3.2.9 on 2021-11-19 00:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.ManyToManyField(related_name='applied_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='saved',
            field=models.ManyToManyField(related_name='saved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default=datetime.date(2021, 11, 19)),
        ),
        migrations.AlterField(
            model_name='application',
            name='close_date',
            field=models.DateField(default=datetime.date(2021, 11, 19)),
        ),
        migrations.AlterField(
            model_name='job',
            name='open_date',
            field=models.DateField(default=datetime.date(2021, 11, 19)),
        ),
    ]
