# Generated by Django 3.2.9 on 2021-11-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211119_0054'),
        ('app', '0002_auto_20211121_1644'),
    ]

    operations = [
    ]
